### ISSUE TITLE
Project hangs after deploying to AWS server.

### ISSUE THREAD

**Issue by hmxa22** [vkononov/fillable-pdf#19] opened 2021-11-12 20:36 UTC
begin
      pdf = FillablePDF.new(Rails.root.to_s + '/public/pdf_contracts/' + contract.template_name)
   rescue Exception => e
        Rails.logger.info('exception - ***')
        Rails.logger.info(e.message)
    ensure
        Rails.logger.info('reached ensure block ')
    end

So  hang the server when i try to create the pdf from .new and didnt even through exception neither ensure msg displayed on production.log.

**Comment by vkononov** [comment] 2021-11-16 08:01
@hmxa22 This is a duplicate of [Issue 18](https://github.com/vkononov/fillable-pdf/issues/18). Please see [this comment](https://github.com/vkononov/fillable-pdf/issues/18#issuecomment-919462582) and [Deployment with Phusion Passenger + Nginx](https://github.com/vkononov/fillable-pdf#deployment-with-phusion-passenger--nginx) for a workaround. If this solves your problem, please close the issue. Thanks.

**Closed** 2021-11-19 15:34 UTC
