### ISSUE TITLE
National characters

### ISSUE THREAD

**Issue by tfader** [vkononov/fillable-pdf#22] opened 2022-07-07 12:56 UTC
Any idea what I'm doing wrong or what should I change?

In any fields with value included national characters, proper value is displayed only when field is "clicked/active"

In printout or preview national characters are invisible.

When I input manually values with national characters, all characters are OKey.

Issue is only when I fill form from RoR application (UTF-8 as default for app and DB).

Examples are attached.
<img width="747" alt="Zrzut ekranu 2022-07-7 o 14 48 02" src="https://user-images.githubusercontent.com/22178012/177778734-d323e285-496d-4409-b3c7-0237c0220ee7.png">
<img width="266" alt="Zrzut ekranu 2022-07-7 o 14 51 00" src="https://user-images.githubusercontent.com/22178012/177778750-15aeeb9f-1313-45cf-8fec-0c8043c3e72e.png">

**Comment by vkononov** [comment] 2022-07-08 02:47
Duplicate of #23.

**Closed by vkononov** 2022-07-08 02:47 UTC
